### ISSUE TITLE
Add numbers to the visual representation of the pens

### ISSUE THREAD

**Issue by Dwkern** [osmi-app/osmi-app#15]
Proposal
=======
Let's make the virtual pens labelled 1, 2, 3.

Why
====
The virtual pens are currently color coded to match the real pens so that the interviewer knows in which order to administer them to the participant. However, the participant will respond with a number to indicate which pen they think has the odor (e.g., 1, 2, or 3). If we were to add numbers to the pens, it would make things that much easier/clearer for the interviewer to record the participant's response.

**Comment by lschumm** [comment]
Adding this with an option in settings to enable/disable numbers.

**Comment by lschumm** [comment]
Resolved in adf6421.
