### ISSUE TITLE
Gender recorded instead of age in data

### ISSUE THREAD

**Issue by Dwkern** [osmi-app/osmi-app#5]
The Problem
==========

After assessments have been performed, the data records gender in place of age. For example, in the following screen "male" is displayed as age:

![img_0001](https://user-images.githubusercontent.com/29662019/27802888-233dbbd6-5fec-11e7-8bf6-8ded53d3b888.PNG)

Debugging Information
=================

Running Osmi version 1.0.0-alpha.1 on an iPod Touch 5G running iOS 9.3.4 (13G35).

**Comment by lschumm** [comment]
Resolved in 76aae0a.
