### ISSUE TITLE
Osmi outputs a tab-delimited files regardless of settings

### ISSUE THREAD

**Issue by Dwkern** [osmi-app/osmi-app#6]
The Issue
=======

No matter what option is selected in Settings > CSV Seperator (Comma or Tab), Osmi outputs tab-separated CSV files.

Debugging Information
=================

Running Osmi version 1.0.0-alpha.1 on an iPod Touch 5G running iOS 9.3.4 (13G35).

**Comment by lschumm** [comment]
Resolved in 1173798.
